### Site Settings ###
title               : Alberto Labarga
description         : >-
                      I turn coffee :coffee: into code,
                      data into insights
                      and problems into opportunities.
baseurl             : ""                               # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : alabarga/alabarga.github.io      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                            # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Alberto Labarga
  image             : https://media.licdn.com/dms/image/v2/C5603AQHZiPQlh1_nPA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1606075403577?e=1749686400&v=beta&t=GiIac4VXJNqeTOfkf4lQV5jTTRb7WIW-8F3J6U_207U
  email             : alberto.labarga@gmail.com
  github            : alabarga
  instagram         : alabarga
  linkedin          : albertolabarga
  twitter           : alabarga
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username
#  behance           : your_username
# dribbble          : your_username
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# kaggle            : your_username
# gitlab            : your_username
#  facebook          : your_username


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Posts ###
permalink: /blog/:title

### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus
  comments: false                                      # Set to true to enable disqus comments
  
### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: alabarga
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - vendor
